### ISSUE TITLE
gem_dir missing

### ISSUE THREAD

**Issue by drolfe** [mpalmer/lvmsync#46]
[root@enc1-blade02 ~]# ruby -v
ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]
[root@enc1-blade02 ~]# gem -v
1.3.7
[root@enc1-blade02 ~]# which vgcfgbackup
/sbin/vgcfgbackup
[root@enc1-blade02 ~]# cat /etc/redhat-release
CentOS release 6.6 (Final)
[root@enc1-blade02 ~]#

The error received:

[root@enc1-blade02 ~]# lvmsync /dev/4tb_raid_vg/kvm102-snap 192.168.10.207:/dev/vm_vg/kvm102_img
/usr/lib/ruby/site_ruby/1.8/rubygems/specification.rb:538:in `method_missing': undefined method `gem_dir' for #<Gem::Specification:0x7f451d7aae40> (NoMethodError)
        from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:265:in `caller_gemspec'
        from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:263:in `each'
        from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:263:in `caller_gemspec'
        from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:289:in `gem_version'
        from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:37:in `version'
        from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.15.1/lib/git-version-bump/version.rb:2
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
        from /usr/lib/ruby/gems/1.8/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /usr/lib/ruby/gems/1.8/gems/git-version-bump-0.15.1/lib/git-version-bump.rb:308
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `polyglot_original_require'
        from /usr/lib/ruby/gems/1.8/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
        from /usr/lib/ruby/gems/1.8/gems/lvmsync-3.3.2/bin/lvmsync:22
        from /usr/bin/lvmsync:19:in `load'
        from /usr/bin/lvmsync:19
[root@enc1-blade02 ~]#

Seems https://rubygems.org/gems/gem_dir/ is missing as a dependency

Regards, Daniel

**Comment by mpalmer** [comment]
Phooey.  This is actually a bug in `git-version-bump`, rather than `lvmsync` itself; I'll leave this issue open, though, until I bump `lvmsync`'s dependencies to avoid the buggy versions of `git-version-bump`.

**Comment by drolfe** [comment]
Hi Is there any work around this issue ?

 I need to use lvmsync again and would love it just to work for now ?

Regards, Daniel

**Comment by john5223** [comment]
Any fix for this? 

-John

**Comment by m4oc** [comment]
I solved this problem using rvm and ruby 1.9.3

**Comment by ajones6** [comment]
m4oc, can you elaborate on how you fixed the problem?
