### ISSUE TITLE
lvmsync stop working on thin pools

### ISSUE THREAD

**Issue by jpmx** [mpalmer/lvmsync#51]
Hello, `lvmsync` stop working with this LVM versions:

```
[root@host3 ~]# lvmsync -v -e 'ssh -i /root/.ssh/id_tacobit -T -x -o Compression=no' /dev/mapper/d1-mtas_snapshot 10.10.1.11:/dev/mapper/d1-mtas
Data source: /dev/mapper/d1-mtas
syscall 'open' failed: Device or resource busy
Note: you cannot run this tool with these options on live metadata.
/usr/local/share/gems/gems/lvmsync-3.3.2/lib/lvm/thin_snapshot.rb:163:in `vg_block_dump': undefined method `inject' for nil:NilClass (NoMethodError)
    from /usr/local/share/gems/gems/lvmsync-3.3.2/lib/lvm/thin_snapshot.rb:111:in `origin_blocklist'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/lib/lvm/thin_snapshot.rb:103:in `flat_origin_blocklist'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/lib/lvm/thin_snapshot.rb:69:in `differences'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/lib/lvm/logical_volume.rb:81:in `changes'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/bin/lvmsync:279:in `dump_changes'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/bin/lvmsync:231:in `block in run_client'
    from /usr/share/ruby/open3.rb:217:in `popen_run'
    from /usr/share/ruby/open3.rb:99:in `popen3'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/bin/lvmsync:228:in `run_client'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/bin/lvmsync:124:in `main'
    from /usr/local/share/gems/gems/lvmsync-3.3.2/bin/lvmsync:357:in `<top (required)>'
    from /usr/local/bin/lvmsync:23:in `load'
    from /usr/local/bin/lvmsync:23:in `<main>'

[root@host3 ~]# lvmsync --version
lvmsync 0.0.0.1.ENOTAG

[root@host3 ~]# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)

[root@host3 ~]# uname -a
Linux host3 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

[root@host3 ~]# lvm version
  LVM version:     2.02.130(2)-RHEL7 (2015-12-01)
  Library version: 1.02.107-RHEL7 (2015-12-01)
  Driver version:  4.33.0

[root@host3 ~]# pvs
  PV         VG   Fmt  Attr PSize PFree
  /dev/sda4  d1   lvm2 a--  1.87t    0

[root@host3 ~]# vgs
  VG   #PV #LV #SN Attr   VSize VFree
  d1     1   6   0 wz--n- 1.87t    0

[root@host3 ~]# lvs --all
  LV              VG   Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  dns             d1   Vwi-aotz--  50.00g tp1         3.66
  [lvol0_pmspare] d1   ewi------- 120.00m
  mtas            d1   Vwi-a-tz--  50.00g tp1         30.97
  mtas_snapshot   d1   Vwi-a-tz-k  50.00g tp1  mtas   30.97
  mysql           d1   Vwi-aotz-- 500.00g tp1         78.97
  tp1             d1   twi-aotz--   1.87t             22.38  11.75
  [tp1_tdata]     d1   Twi-ao----   1.87t
  [tp1_tmeta]     d1   ewi-ao---- 120.00m
  www             d1   Vwi-aotz-- 100.00g tp1         17.19
```

**Comment by mpalmer** [comment]
Presumably closed by #54.
